### ISSUE TITLE
Raw Capability doesn't collect variable length utf8

### ISSUE THREAD

**Issue by f0rodo** [hotg-ai/runic_flutter#11]
Currently, we are trying to make a rune which needs decode to 10 numbers:

it looks like the [length is hardcoded currently and may be causing issues.](
https://github.com/hotg-ai/runic_flutter/blob/c6a05ba536d236ba62cef3e012ff3b37240adc92/lib/widgets/capabilities/raw_capability_widget.dart#L24) We get no data out from the decode utf8 or the parse node which indicates an issue with getting text out of the raw capability widget.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/56056337/154196176-4649be5a-f9ca-40f7-bf93-45d876cfaaec.png">

<img width="785" alt="image" src="https://user-images.githubusercontent.com/56056337/154196271-1c8280b7-fecd-4892-b36c-7d5b747757ad.png">

I get all 0000

![image](https://user-images.githubusercontent.com/56056337/154196308-3c761bee-2ef1-4738-9286-0ecf3a08a7a6.png)

**Comment by Ge-te** [comment]
This seems to be an issue with the C++ runtime

**Comment by Ge-te** [comment]
Fixed in latest version of app
