### ISSUE TITLE
Ensure that `device_registered_$PROJECTID` is called every time a new qr code is scanned

### ISSUE THREAD

**Issue by f0rodo** [hotg-ai/runic_flutter#16]
https://hotg-ai.slack.com/archives/C031FDRPGKV/p1645141184366489

The video above shows the issue. Additionally, have the heartbeat send the device_registered_$ProjectID regularly just to be sure.

**Comment by Ge-te** [comment]
This should be solved with https://github.com/hotg-ai/runic_flutter/pull/18
