### ISSUE TITLE
Rune not loading by scanning the QR code using the Runic mobile app 

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/runic_flutter#3]
@Ge-te,  When I am trying to load the model on the mobile device by scanning the QR code using the Runic mobile app, it keeps on loading on my mobile phone and doesn't load the rune.

I tried this on:
  1) examples/person_detection
  2) examples/gesture

**Comment by Ge-te** [comment]
Can you share the rune(s)? Will try to debug it
