### ISSUE TITLE
MicroSpeech model keeps loading on Runic mobile app

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/runic_flutter#9]
After scanning the QR code through the runic app, the rune keeps on loading. It never gets deployed. We will have to fix it asap as it is one of the templates for Q-hack.

**Comment by f0rodo** [comment]
@Ge-te this is high priority for sure.

**Comment by Ge-te** [comment]
@f0rodo @Mohit0928 Ok going to implement audio in new app now

**Comment by Ge-te** [comment]
This is resolved
